version: 2

sphinx:
  configuration: docs/conf.py

formats: all

python:
   version: 3.7
   install:
      - requirements: requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: setuptools
        path: another/package
   system_packages: true
