language: python
sudo: yes
dist: xenial

branches:
  only:
    - master

python:
  - "3.7"  # 3.7 development branch
  
install:
  - pip install pyinstaller
  - pip install numpy
  - pip install scipy
  - pip install matplotlib

script:
  - cd octadist/
  - pyinstaller --onefile --windowed --version-file=../version.txt -n OctaDist-run main.py
#  - python src/main.py

