language: python
sudo: yes
dist: xenial

branch:

python:
  - "3.7"  # 3.7 development branch
  
install:
  - pip install pyinstaller
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install rmsd

script:
  - cd octadist/
  - pyinstaller --onefile --windowed --version-file=../version.txt -n OctaDist-Run-Test main.py
#  - python src/main.py

