language: python
sudo: yes
dist: xenial

branches:
  only:
    - nightly-build

python:
  - "3.7"  # 3.7 development branch
  
install:
  - pip install pyinstaller
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install rmsd

script:
  - cd octadist_gui/
  - pyinstaller --onefile --windowed --version-file=../version.txt -n OctaDist-Run-Test main.py
#  - python src/main.py

