language: python
sudo: yes
dist: xenial

branches:
  only:
    - master

python:
  - "3.7"  # 3.7 development branch
  
install:
  - pip install -r requirements.txt

script:
  - cd src/
  - pyinstaller --onefile main.py
#  - python src/main.py


